{% set name = "ipytablewidgets" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipytablewidgets-{{ version }}.tar.gz
  sha256: 08691bfff98b526932bfe8665495f9fb4e091827f0f93b5f0713135d6d1b86cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - jupyter_packaging >=0.10,<2
    - jupyterlab >=3.0.0,<3.7
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.5.0,<9
    - traitlets >=4.3.0
    - traittypes >=0.0.6
    - numpy >=1.10.4,<3.0.0
    - pandas >=1.0.0,<3.0.0
    - lz4

test:
  imports:
    - ipytablewidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/progressivis/ipytablewidgets
  summary: A set of widgets to help facilitate reuse of large tables across widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xtianpoli
    - ocefpaf
